import { Inter } from "next/font/google";
import Image from "next/image";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-white text-black"}>
        <header className="flex justify-between items-center px-24 py-5 bg-white">
          <Image
            className="relative flex-grow-0 "
            src="/assets/logo.png"
            alt="Next.js Logo"
            width={162.57}
            height={24}
            priority
          />
          <div
            style={{ backgroundColor: "#F2F2F2", width: "360px" }}
            className="flex h-11 px-5 gap-3 justify-left items-center rounded-l-full rounded-r-full"
          >
            <i class="bi bi-search"></i>
            <input type="text" className="w-full bg-transparent" placeholder="Search your favourite groups in ATG" />
          </div>

          <button className="flex">
            Create account.{" "}
            <span className="text-blue-700 font-bold pl-1">It's free</span>
            <svg
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g clip-path="url(#clip0_1_822)">
                <path d="M7 10L12 15L17 10H7Z" fill="#2E2E2E" />
              </g>
              <defs>
                <clipPath id="clip0_1_822">
                  <rect width="24" height="24" fill="white" />
                </clipPath>
              </defs>
            </svg>
          </button>
        </header>
        {children}
      </body>
    </html>
  );
}
